/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CvChat {
    }
}
declare global {
    interface HTMLCvChatElement extends Components.CvChat, HTMLStencilElement {
    }
    var HTMLCvChatElement: {
        prototype: HTMLCvChatElement;
        new (): HTMLCvChatElement;
    };
    interface HTMLElementTagNameMap {
        "cv-chat": HTMLCvChatElement;
    }
}
declare namespace LocalJSX {
    interface CvChat {
    }
    interface IntrinsicElements {
        "cv-chat": CvChat;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv-chat": LocalJSX.CvChat & JSXBase.HTMLAttributes<HTMLCvChatElement>;
        }
    }
}
