/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CvChat {
        /**
          * Asks a question as if the visitor had typed it and pressed Enter.
         */
        "ask": (question: string) => Promise<void>;
        /**
          * @default ''
         */
        "collection": string;
        /**
          * Base URL of the ask endpoint; the collection name is appended.
          * @default 'https://ai-worker.henrik-becker.workers.dev/ask/'
         */
        "endpoint": string;
        /**
          * @default 'Something went wrong while contacting my brain.'
         */
        "error": string;
        /**
          * Puts the cursor in the question box.
         */
        "focusInput": () => Promise<void>;
        /**
          * @default 'Ask my CV bot anything...'
         */
        "placeholder": string;
    }
}
declare global {
    interface HTMLCvChatElement extends Components.CvChat, HTMLStencilElement {
    }
    var HTMLCvChatElement: {
        prototype: HTMLCvChatElement;
        new (): HTMLCvChatElement;
    };
    interface HTMLElementTagNameMap {
        "cv-chat": HTMLCvChatElement;
    }
}
declare namespace LocalJSX {
    interface CvChat {
        /**
          * @default ''
         */
        "collection"?: string;
        /**
          * Base URL of the ask endpoint; the collection name is appended.
          * @default 'https://ai-worker.henrik-becker.workers.dev/ask/'
         */
        "endpoint"?: string;
        /**
          * @default 'Something went wrong while contacting my brain.'
         */
        "error"?: string;
        /**
          * @default 'Ask my CV bot anything...'
         */
        "placeholder"?: string;
    }
    interface IntrinsicElements {
        "cv-chat": CvChat;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv-chat": LocalJSX.CvChat & JSXBase.HTMLAttributes<HTMLCvChatElement>;
        }
    }
}
