name: Build & Release cv-chat

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: List dist
        run: ls -R dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            www/build/cv-chat.js
            www/build/cv-chat.esm.js
            www/build/cv-chat.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
