name: Build & Release cv-chat

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
  
      - name: List built files
        run: ls -R dist/ www/build/

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
            files: |
              dist/*
              dist/**/*    # inkluderar undermappar
              www/build/*
              www/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
